import struct

HEADER_FORMAT = "!4s B B I I Q H I"
PROTOCOL_ID = b"CCLP"
VERSION = 2

HEADER_SIZE = struct.calcsize(HEADER_FORMAT)

MSG_INIT = 0x01
MSG_INIT_ACK = 0x02
MSG_SNAPSHOT = 0x03
MSG_EVENT = 0x04
MSG_ACK = 0x05
MSG_GAME_OVER = 0x06
